name: prometheus-bin
version: 2.50.1
category: app-metrics
annotations:
  subsets:
    rules:
      devel:
      - ^/usr/include/
      portage:
      - ^/var/db/pkg/
description: The Prometheus monitoring system and time series database.
uri:
- https://github.com/prometheus/prometheus
license: Apache-2.0
labels:
  DEPEND: sys-apps/shadow
  IUSE: amd64 arm64
  emerge.packages: app-metrics/prometheus-bin
  kit: core-server-kit
  original.package.name: app-metrics/prometheus-bin
  original.package.slot: "0"
  original.package.version: 2.50.1
